### PR TITLE
Fixed that the plugin stops working when adding another classes

### LINKED ISSUE #31: Using the Swift .xctemplate will fail with multiple classes
Once you create a new class other than the default class included in the xctemplate, the plugin will not load. 

ex: 
Add class `class SomeClass {`} at the top of the .swift file included in the template. 
Potentially a Swift module issue or an omitted parameter in the xctemplate?

### PR DESCRIPTION
**Pull request by creinders**
It seems that it is unclear on which class Xcode calls pluginDidLoad.
Because of that the plugin stopped working unexpectedly.
To fix that I extended NSObject and moved pluginDidLoad there. I did
the fix for both objective c and swift. I described my solution also
here http://stackoverflow.com/a/30000663/1442208

This closes #31, and #32.

### CODE REVIEW

**Comment by kattrali** [comment]
Whoa! That is incredibly clever. I think this might be a good solution.

**Comment by onmyway133** [comment]
This works for me, thanks 🎉

**Comment by 0xced** [comment]
Adding `+pluginDidLoad:` as a category on NSObject seems pretty dangerous to me.

> It seems that it is unclear on which class Xcode calls pluginDidLoad.

Xcode calls `pluginDidLoad` on the [principal class](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/Foundation/Classes/NSBundle_Class/index.html#//apple_ref/occ/instp/NSBundle/principalClass). When the principal class is a Swift class, the `NSPrincipalClass` Info.plist key must include the module name. This is what I did for [KZLinkedConsole](https://github.com/krzysztofzablocki/KZLinkedConsole/commit/ccff9b75d55d46bc0162b85d7cbed05810ed5e05#diff-4fa8b26dcf1c5c2810ac97f461354075R46).

I’d suggest to revert this change.

**Comment by kattrali** [comment]
@0xced Including the module name was the missing information, I think. Agreed on the danger, but at the time it certainly smelled like a bug. 

Reverting and updating the docs with a note.

**Comment by 0xced** [comment]
I [struggled](https://twitter.com/0xced/status/729376731191201794) yesterday, happy to share the solution. Having the correct principal class also makes it [unnecessary to restart Xcode](https://github.com/alcatraz/Alcatraz/blob/00bf07bf07e52773e72a3ae24df6147f2361c027/Alcatraz/Installers/ATZPluginInstaller.m#L161) after installing a plugin.

**Comment by kattrali** [comment]
Ah! Awesome. Thanks, @0xced.

**Comment by onmyway133** [comment]
@0xced thanks, forget about this Swift namespace thingy

**Comment by 0xced** [comment]
I have a clean solution for this in #49. The `NSPrincipalClass` key will be correct for both Objective-C and Swift.

**Pull request merged**
